import { SiteHeader } from "@/components/site-header"
import { SiteFooter } from "@/components/site-footer"
import { Sparkles, Zap, Package, Palette } from "lucide-react"

export default function AboutPage() {
  return (
    <div className="flex flex-col min-h-svh">
      <SiteHeader />

      <main className="flex-1">
        <div className="max-w-4xl mx-auto px-4 py-16 sm:py-24">
          {/* Hero Section */}
          <div className="text-center mb-16">
            <h1 className="text-4xl sm:text-5xl font-bold tracking-tight mb-4">
              About This Project
            </h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Built with intention. Designed for speed. Open for everyone.
            </p>
          </div>

          {/* Main Content */}
          <div className="prose prose-gray dark:prose-invert max-w-none">
            <div className="bg-muted/50 rounded-lg p-8 mb-12 border">
              <p className="text-lg leading-relaxed mb-6">
                At <span className="text-primary font-bold">Vaatun</span>, we&apos;ve always believed something simple but often ignored in software: <strong>good branding is a competitive advantage</strong>, and <strong>great UI/UX is the fastest way to make people genuinely enjoy using a product</strong>. Most tools treat illustrations as an afterthought—static assets thrown into a folder, impossible to recolor, inconsistent in style, and painful to maintain.
              </p>
              <p className="text-lg leading-relaxed mb-6">
                We wanted the opposite.
              </p>
              <p className="text-lg leading-relaxed mb-6">
                The unDraw Illustrations Registry was built to give teams a <strong>zero-friction, on-demand illustration system</strong>—simple like Remix Icons, but for full SVG scenes. One command, and you have a fully customizable, brand-aligned illustration as a React component. No manual SVG editing. No tweaking XML structure. No dependency on external CDNs. Just clean components you own.
              </p>
              <p className="text-lg leading-relaxed mb-6">
                We chose unDraw intentionally: an MIT-licensed, beautifully consistent illustration library that pairs perfectly with the &ldquo;components you own&rdquo; philosophy behind modern design systems like shadcn/ui. It lets us deliver visuals that are stable, theme-able, and easy to adapt across the board—from product screens to marketing pages to autogenerated PDFs.
              </p>
              <p className="text-lg leading-relaxed mb-6">
                This project was also born out of our own needs. Vaatun products, the Vaatun website, and our ONDC work all required illustrations that were:
              </p>
              <ul className="list-disc pl-6 mb-6 space-y-2 text-lg">
                <li>branded,</li>
                <li>consistent,</li>
                <li>easy to recolor,</li>
                <li>and available <strong>exactly when needed</strong>, without maintenance overhead.</li>
              </ul>
              <p className="text-lg leading-relaxed mb-6">
                Instead of repeatedly reinventing the wheel, we built a registry that anyone—inside Vaatun or outside—can use to ship polished visuals at speed.
              </p>
              <p className="text-lg leading-relaxed">
                This is part of our broader philosophy: <strong>tools should empower, not slow down</strong>. If something improves clarity, usability, or aesthetic quality for our customers, we invest in it, automate it, and open-source it when possible.
              </p>
            </div>

            {/* Author */}
            <div className="border-l-4 border-primary pl-6 mb-16">
              <p className="text-lg font-medium mb-1">— Vaibhav</p>
              <p className="text-muted-foreground">CTO, Vaatun</p>
            </div>

            {/* Key Features Grid */}
            <div className="mb-16">
              <h2 className="text-3xl font-bold mb-8 text-center">Why This Matters</h2>
              <div className="grid sm:grid-cols-2 gap-6">
                <div className="bg-background border rounded-lg p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="p-2 bg-primary/10 rounded-lg">
                      <Zap className="h-5 w-5 text-primary" />
                    </div>
                    <h3 className="text-xl font-semibold">Zero Friction</h3>
                  </div>
                  <p className="text-muted-foreground">
                    One command installs a fully typed React component. No manual downloads, no SVG wrangling, no build pipeline changes.
                  </p>
                </div>

                <div className="bg-background border rounded-lg p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="p-2 bg-primary/10 rounded-lg">
                      <Palette className="h-5 w-5 text-primary" />
                    </div>
                    <h3 className="text-xl font-semibold">Brand Aligned</h3>
                  </div>
                  <p className="text-muted-foreground">
                    Illustrations automatically use your CSS variables. Change your brand color once, update everywhere instantly.
                  </p>
                </div>

                <div className="bg-background border rounded-lg p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="p-2 bg-primary/10 rounded-lg">
                      <Package className="h-5 w-5 text-primary" />
                    </div>
                    <h3 className="text-xl font-semibold">Components You Own</h3>
                  </div>
                  <p className="text-muted-foreground">
                    No external dependencies. No CDN risk. Components live in your codebase, version controlled and auditable.
                  </p>
                </div>

                <div className="bg-background border rounded-lg p-6">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="p-2 bg-primary/10 rounded-lg">
                      <Sparkles className="h-5 w-5 text-primary" />
                    </div>
                    <h3 className="text-xl font-semibold">Consistent Style</h3>
                  </div>
                  <p className="text-muted-foreground">
                    All 1,362 illustrations share a unified design language. Build cohesive experiences without the visual chaos.
                  </p>
                </div>
              </div>
            </div>

            {/* Philosophy Section */}
            <div className="bg-primary/5 rounded-lg p-8 border border-primary/20">
              <h2 className="text-2xl font-bold mb-4 text-center">The Vaatun Philosophy</h2>
              <p className="text-lg text-center text-muted-foreground max-w-2xl mx-auto">
                Tools should empower, not slow down. If something improves clarity, usability, or aesthetic quality for our customers, we invest in it, automate it, and open-source it when possible.
              </p>
            </div>
          </div>
        </div>
      </main>

      <SiteFooter />
    </div>
  )
}
